import 'package:feature_account/feature_account.dart';
import 'package:feature_auth/feature_auth.dart';
import 'package:feature_journal/feature_journal.dart';
import 'package:feature_session/feature_session.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:go_router/go_router.dart';

part 'routes.g.dart';

/// The app's route table (ADR 0016): every screen has a typed route here,
/// generated by go_router_builder from these declarations, and nowhere
/// else. Features never see it — they ask for other features' screens
/// through their navigator (ADR 0015), and the app answers with a route.
///
/// Nothing travels as `extra`: a route carries only what its location can
/// say, so every screen can be reached from its location alone.

/// Where a signed-out user is sent, and the only screen they can see.
@TypedGoRoute<SignInRoute>(path: '/sign-in', name: 'signIn')
class const SignInRoute() extends GoRouteData with $SignInRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) => const SignInPage();
}

/// Home: the journal. Every other signed-in screen sits under it, so the
/// back button always leads here.
@TypedGoRoute<JournalRoute>(
  path: '/',
  name: 'journal',
  routes: [
    TypedGoRoute<AccountRoute>(path: 'account', name: 'account'),
    TypedGoRoute<ConsentRoute>(path: 'consent', name: 'consent'),
    TypedGoRoute<SessionRoute>(path: 'session', name: 'session'),
    TypedGoRoute<EntryRoute>(path: 'entries/:id', name: 'entry'),
  ],
)
class const JournalRoute() extends GoRouteData with $JournalRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const JournalPage();
}

/// One filed entry, by its id; the screen reads it back itself.
@immutable
class const EntryRoute({required final String id})
    extends GoRouteData
    with $EntryRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) =>
      EntryPage(entryId: id);
}

/// A journaling session, pushed so the journal can reload when it pops.
/// `?resume=true` picks the stored session up; the session reads it back
/// itself, so the location is all there is to carry.
@immutable
class const SessionRoute({final bool resume = false})
    extends GoRouteData
    with $SessionRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) =>
      SessionPage(resume: resume);
}

/// The consent screen, pushed for its [ConsentOutcome]. The route owns the
/// bloc, which is the authority on the answer: `granted` only after the
/// server recorded it. The provider closes the bloc with the route.
@immutable
class const ConsentRoute() extends GoRouteData with $ConsentRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) => BlocProvider(
    create: (_) => GetIt.I<ConsentBloc>()..add(const ConsentEvent.loaded()),
    child: const ConsentPage(),
  );
}

/// The account screen, with a consent bloc of its own for the section that
/// takes consent back; the journal asks the server again before every
/// session, so nothing has to be shared between the two routes.
@immutable
class const AccountRoute() extends GoRouteData with $AccountRoute {
  @override
  Widget build(BuildContext context, GoRouterState state) => BlocProvider(
    create: (_) => GetIt.I<ConsentBloc>()..add(const ConsentEvent.loaded()),
    child: const AccountPage(),
  );
}
